name: Continuous Integration (Branch)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Test (${{ matrix.python }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    container:
      image: python:${{ matrix.python }}
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Commit Linter
        uses: wagoid/commitlint-github-action@v5
      - id: install
        name: Install requirements
        run: |
          pip install clinner pip poetry --upgrade
          python make install
      - id: black
        name: Code format checking
        run: python make black --check .
      - id: isort
        name: Imports order checking
        run: python make isort --check .
      - id: ruff
        name: Code lint
        run: python make ruff .
      - id: tests
        name: Tests
        run: python make test
